language: cpp
dist: trusty
sudo: required
matrix:
  include:
    - compiler: clang
      os: linux
    - compiler: clang
      env: SCAN_BUILD=true
      os: linux
    - compiler: gcc
      os: linux
    - compiler: gcc
      env: HOST=i686-w64-mingw32
      os: linux
    - compiler: clang
      os: osx
    - compiler: clang
      env: SCAN_BUILD=true
      os: osx

before_install:
  - if [[ -n $SCAN_BUILD ]]; then
      if [[ $TRAVIS_OS_NAME = "osx" ]]; then
        . scan-build-install.sh;
      else
        export SCAN_BUILD_PATH=scan-build;
      fi
    fi
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      sudo apt-get update -qq;
      if [ -z "$HOST" ]; then
        sudo apt-get install -y libpulse-dev libasound2-dev pulseaudio doxygen;
      else
        sudo apt-get install -qq mingw-w64 mingw-w64-tools;
      fi
    fi
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
       brew update;
       brew uninstall libtool && brew install libtool;
       brew uninstall cmake && brew install cmake;
    fi
before_script:
  - cmake --version
  - mkdir build
  - cd build
  - if [ ! -z "$HOST" ]; then
      $SCAN_BUILD_PATH cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain-cross-mingw.cmake ..;
    else
      $SCAN_BUILD_PATH cmake ..;
    fi
script:
  - echo $SCAN_BUILD_PATH
  - $SCAN_BUILD_PATH make
  - if [[ $TRAVIS_OS_NAME = "linux" ]]; then
      if [ -z "$HOST"  ]; then
        make test ARGS=-V;
      fi
    fi
addons:
  apt:
    packages:
      - clang
